name: Genshin Impact

on:
  workflow_dispatch:
  schedule:
    - cron: 0 22 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run script
        run: node index.js
